name: AmarPet application build for deployment environment and deploy to the development server

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - master

jobs:
  build:
    name: Production build process
    runs-on: ubuntu-latest
    steps:
      - name: Set up Actions
        uses: actions/checkout@v3

  deploy:
    name: Production deploy process
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Print secret for debugging (masked)
        run: |
          echo "HOST is ${{ secrets.HOST }}"
          echo "USERNAME is ${{ secrets.USERNAME }}"
          echo "PORT is ${{ secrets.PORT }}"
      - name: Production server access via SSH access
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/backend-api-task
            make pull
            make stop
            make start
            make down
            make migrate
            make optimize
            make up
